services:
  db:
    image: mysql:8.0
    container_name: diplome-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diplomemmi
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - diplome-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplome-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/diplomemmi?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APPLICATION_SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    networks:
      - diplome-network

  front:
    build:
      context: ../front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    container_name: diplome-front
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - diplome-network

volumes:
  db_data:

networks:
  diplome-network:
    driver: bridge
